### ISSUE TITLE
Crash While Loading

### ISSUE THREAD

**Issue by CaptainAhmed18** [grondag/Pyroclasm#24]
While Loading Minecraft, I Got This:

[15:57:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:57:33] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:57:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:57:33] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2838 for Minecraft 1.12.2 loading
[15:57:33] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_211, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_211
[15:57:33] [main/INFO] [FML]: Searching C:\Users\user\AppData\Roaming\.minecraft\mods for mods
[15:57:33] [main/INFO] [FML]: Searching C:\Users\user\AppData\Roaming\.minecraft\mods\1.12.2 for mods
[15:57:33] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in acuity-mc1.12.2-0.0.0.521-alpha.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[15:57:33] [main/WARN] [FML]: The coremod AcuityCore (grondag.acuity.AcuityCore) is not signed!
[15:57:33] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in EvilNotchLib-1.2.3-SNAPSHOt-78.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[15:57:33] [main/WARN] [FML]: The coremod evilnotchlib-transformer_fixes (com.evilnotch.lib.asm.FMLCorePlugin) is not signed!
[15:57:33] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in mclib-1.0.2-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[15:57:33] [main/WARN] [FML]: The coremod McLib core mod (mchorse.mclib.core.McLibCM) is not signed!
[15:57:33] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_E3.jar
[15:57:33] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.5-168.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[15:57:33] [main/WARN] [FML]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[15:57:33] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.9-97.jar
[15:57:34] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:57:34] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[15:57:34] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[15:57:34] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.10 Source=file:/C:/Users/user/AppData/Roaming/.minecraft/mods/VanillaFix-1.0.9-97.jar Service=LaunchWrapper Env=CLIENT
[15:57:34] [main/WARN] [FML]: The coremod VanillaFixLoadingPlugin (org.dimdev.vanillafix.VanillaFixLoadingPlugin) is not signed!
[15:57:34] [main/INFO] [org.dimdev.vanillafix.VanillaFixLoadingPlugin]: Initializing StacktraceDeobfuscator
[15:57:34] [main/INFO] [org.dimdev.vanillafix.VanillaFixLoadingPlugin]: Found MCP method mappings: methods-20180618-1.12.csv
[15:57:34] [main/INFO] [org.dimdev.vanillafix.VanillaFixLoadingPlugin]: Done initializing StacktraceDeobfuscator
[15:57:34] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[15:57:34] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:57:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:57:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:57:34] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[15:57:34] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[15:57:34] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[15:57:34] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[15:57:34] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\user\AppData\Roaming\.minecraft\mods\OptiFine_1.12.2_HD_U_E3.jar
[15:57:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:57:35] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[15:57:35] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[15:57:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:57:35] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[15:57:35] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@2e380628
[15:57:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:57:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:57:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:57:36] [main/INFO] [STDOUT]: [com.evilnotch.lib.asm.ConfigCore:load:21]: Loading CoreMod Configurations for ASM:
[15:57:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:57:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:57:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:57:36] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:57:36] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[15:57:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:57:36] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[15:57:36] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[15:57:36] [main/INFO] [Quark ASM]: Transforming net.minecraft.enchantment.EnchantmentHelper
[15:57:36] [main/INFO] [Quark ASM]: Applying Transformation to method (Names [getEnchantments, func_82781_a] Descriptor (Lnet/minecraft/item/ItemStack;)Ljava/util/Map;)
[15:57:36] [main/INFO] [Quark ASM]: Located Method, patching...
[15:57:36] [main/INFO] [Quark ASM]: Located patch target node INVOKEVIRTUAL net/minecraft/item/ItemStack.func_77986_q ()Lnet/minecraft/nbt/NBTTagList;
[15:57:36] [main/INFO] [Quark ASM]: Patch result: true
[15:57:37] [main/INFO] [STDOUT]: [com.evilnotch.lib.asm.Transformer:transform:46]: Transforming: net.minecraft.entity.Entity
[15:57:37] [main/INFO] [STDOUT]: [com.evilnotch.lib.asm.ASMHelper:getCachedMethodNode:97]: using cached node:
[15:57:37] [main/INFO] [STDOUT]: [com.evilnotch.lib.asm.ASMHelper:getCachedMethodNode:97]: using cached node:
[15:57:37] [main/INFO] [STDOUT]: [com.evilnotch.lib.asm.CapTransformer:transFormEntityCaps:86]: found injection point for entity.onEntityUpdate()
[15:57:37] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.com.evilnotch.lib.asm.Transformer' was detected and will no longer process meta class data
[15:57:37] [main/INFO] [Quark ASM]: Transforming net.minecraft.entity.Entity
[15:57:37] [main/INFO] [Quark ASM]: Applying Transformation to method (Names [move, func_70091_d] Descriptor (Lnet/minecraft/entity/MoverType;DDD)V)
[15:57:37] [main/INFO] [Quark ASM]: Located Method, patching...
[15:57:37] [main/INFO] [Quark ASM]: Located patch target node INVOKEVIRTUAL net/minecraft/entity/Entity.func_184231_a (DZLnet/minecraft/block/state/IBlockState;Lnet/minecraft/util/math/BlockPos;)V
[15:57:37] [main/INFO] [Quark ASM]: Patch result: true
[15:57:37] [main/INFO] [Quark ASM]: Located Method, patching...
[15:57:37] [main/INFO] [Quark ASM]: Located patch target node INVOKEVIRTUAL net/minecraft/entity/Entity.func_145775_I ()V
[15:57:37] [main/INFO] [Quark ASM]: Patch result: true
[15:57:37] [main/INFO] [Acuity Rendering API]: Patching net.minecraft.client.Minecraft
[15:57:37] [main/INFO] [Acuity Rendering API]: Patching net.minecraft.client.renderer.vertex.VertexFormatElement
[15:57:37] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.grondag.acuity.ASMTransformer' was detected and will no longer process meta class data
[15:57:37] [main/INFO] [Quark ASM]: Transforming net.minecraft.client.renderer.EntityRenderer
[15:57:37] [main/INFO] [Quark ASM]: Applying Transformation to method (Names [renderWorldPass, func_175068_a] Descriptor (IFJ)V)
[15:57:37] [main/INFO] [Quark ASM]: Located Method, patching...
[15:57:37] [main/INFO] [Quark ASM]: Located patch target node INVOKEVIRTUAL net/minecraft/client/renderer/EntityRenderer.func_78479_a (FI)V
[15:57:37] [main/INFO] [Quark ASM]: Patch result: true
[15:57:37] [main/FATAL] [mixin]: Mixin prepare failed preparing client.MixinBufferBuilder in mixins.vanillafix.crashes.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.vanillafix.crashes.json:client.MixinBufferBuilder target net.minecraft.client.renderer.BufferBuilder was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.vanillafix.crashes.json:client.MixinBufferBuilder target net.minecraft.client.renderer.BufferBuilder was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) [VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [VanillaFix-1.0.9-97.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_211]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211]
	at java.lang.Class.forName(Unknown Source) [?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[15:57:37] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.vanillafix.crashes.json:client.MixinBufferBuilder] from phase [DEFAULT] in config [mixins.vanillafix.crashes.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinPrepareError(MixinTransformer.java:728) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:650) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[VanillaFix-1.0.9-97.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.vanillafix.crashes.json:client.MixinBufferBuilder target net.minecraft.client.renderer.BufferBuilder was already transformed.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) ~[VanillaFix-1.0.9-97.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[VanillaFix-1.0.9-97.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
Exception in thread "main" [15:57:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:57:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[15:57:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[15:57:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[15:57:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[15:57:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[15:57:37] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Try To Fix This Issue.

**Comment by grondag** [comment]
Thank you for your interest in Pyroclasm.  I'm sad to say I'm no longer supporting the 1.12 version.  A new version will be released eventually for Minecraft 1.14 or maybe 1.15 but there's a mountain of code that needs to be ported still for that to happen.
